vla_path: "/mnt/data-qilin/openvla-7b/"                          

pizza_dir: "/mnt/data-xiaofan/robot_dataset/simpler_data/"                       
dataset_name: "simpler"                                
run_root_dir: "/mnt/data-qilin/openvla_simpler_cl/0216-CL-FFT/"                         
adapter_tmp_dir: "/mnt/data-qilin/openvla_simpler_cl/0216-CL-FFT/adapter/"                                                      

epochs: 200                                                
batch_size: 3                                        

save_steps: 1000                                          
learning_rate: 1.5e-5                                     
grad_accumulation_steps: 2                            
image_aug: True                                          

use_lora: True                                          
lora_rank: 16                                            
lora_dropout: 0.0                                                                       